---
title: "BRMS"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

```{r, message = FALSE, warning = FALSE}
library(rstan)
library(brms)
library(loo)
library(tidyverse)
library(bayesplot)
theme_set(bayesplot::theme_default())
library(here)
setwd(here())
```

```{r}
rstan_options(auto_write = TRUE) #cache model
options(mc.cores = parallel::detectCores()) #multiple cores for multiple chains
```


### The Data

The regressand is the price of an item. Regressors include the UPC of the item, the specific store, the supermarket brand, and the region.

```{r}
model_data <- read.csv("data/model_data.csv")
colnames(model_data) <- c("Price", "store_id", "UPC", "banner_id", "region_id")
model_data$store_id <- as.factor(model_data$store_id)
model_data$UPC <- as.factor(model_data$UPC)
model_data$price_norm = scale(model_data$Price)
```


### Priors

```{r}
priors <- get_prior(formula = price_norm ~ (1|region_id/banner_id) - 1 + store_id + UPC,              data = model_data)
unique(priors$class)
```


```{r}
prior1 <- c(set_prior("normal(0,1)", class = "b"), #includes intercept I think...
            set_prior("exponential(1)", class = "sigma"),
            set_prior("exponential(1)", class = "sd"))
```



### The Model

```{r}
m1 <- brm(formula = price_norm ~ (1|region_id/banner_id) - 1 + store_id + UPC,
              data = model_data, 
              family = gaussian(),
              prior = prior1,
              cores = 4,
              chains = 4,
          iter = 5000,
          warmup = 1000,
              seed = 1)
```

Seems to work, now to get ready to upload to AWS.


```{r}
#Data
stan_data <- make_standata(formula = price_norm ~ (1|region_id/banner_id) - 1 + store_id + UPC, 
              data = model_data)
save(stan_data,  file = "data/brms_data.rda")
```

```{r}
#stan script
make_stancode(price_norm ~ (1|region_id/banner_id) - 1 + store_id + UPC, 
                  data = model_data, #note- NOT stan_data
                  family = gaussian(),
                  prior = prior1,
                  save_model = "models/bmrs_model.stan")
```


```{r}
m1 <- stanc(file = "models/bmrs_model.stan")
m1 <- stan_model(stanc_ret = m1)
fit1 <- sampling(m1, #use sampling function, rather than stan()
                warmup=1000, #
                iter=6000, #total iterations including warmup
                seed=1, #ensures reproducibility 
                data=stan_data, 
                chains = 4, #each chain has different initial condition which helps to find pathological neighborhood of posterior
                cores = getOption("mc.cores", 1L),
                verbose = FALSE,
                refresh = 1000)
```




### Analysis

```{r}
summary(m1, 
        probs = c(0.025, 0.975),
        digits = 2)
```

```{r}
prior_summary(m1)
```

```{r}
plot(m1, N = 2, ask = FALSE)
```

```{r}
plot(conditional_effects(m1), points = TRUE) 
```

```{r}
pp_check(m1)
```

```{r}
loo(m1)
```


```{r}
names(m1)
```

```{r}
sims <- as.matrix(m1)
dim(sims)
colnames(sims)
```

```{r}
posterior_interval(sims, prob = 0.95, pars = 'region_idNewYork')
apply(sims, 2, median)
```


```{r}
summary(residuals(m1)) # not deviance residuals
```

```{r}
cov2cor(vcov(m1))
```

```{r}
launch_shinystan(m1)
```

```{r}
y <- as.numeric(model_data$price_norm)
y_rep <- posterior_predict(m1)
```

